//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniGoogle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLog
    {
        public int MessageID { get; set; }
        public string MessageText { get; set; }
        public string FullMessage { get; set; }
        public string FunctionName { get; set; }
        public string PageName { get; set; }
        public string AppName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string EntityErrors { get; set; }
        public string ObjectData { get; set; }
    }
}
