//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniGoogle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndexedPage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IndexedPage()
        {
            this.PageKeywords = new HashSet<PageKeyword>();
        }
    
        public int PageID { get; set; }
        public string PageName { get; set; }
        public string PageURL { get; set; }
        public int ParentID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ParentDirectory { get; set; }
        public Nullable<bool> IsIndexed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageKeyword> PageKeywords { get; set; }
    }
}
